site_name:           SOM
repo_url:            https://github.com/andreasdominik/SOM.jl.git
site_description:    Description
site_author:         Andreas Dominik
theme:               readthedocs

markdown_extensions:
    - codehilite
    - extra
    - tables
    - fenced_code
#    - mdx_math # For LaTeX

extra_css:
    - assets/Documenter.css

extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
    - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
  - Introduction: index.md
  - Tutorials:
      - Quick Start: tutorials/firstTutorial.md
  - API:
      - Types: api/types.md
      - Training: api/soms.md
      - Visualisation: api/visualisations.md
  - License: LICENSE.md
